In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import confusion_matrix
from sklearn.impute import SimpleImputer 

In [2]:
df = pd.read_csv(".\DATA\wine.csv")

X = df.iloc[:, :-1].values
y = df.iloc[:, -1].values

# deal with missing data
Imputer = SimpleImputer(missing_values=np.nan, strategy='mean')
Imputer.fit(X[:, :])
X[:, :] = Imputer.transform(X[:, :])

# split data
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=0)

# normalize
sc_X = StandardScaler()
X_train = sc_X.fit_transform(X_train)
X_test = sc_X.transform(X_test)

In [3]:
# logistic regression
log_reg = LogisticRegression(random_state=0)
log_reg.fit(X_train, y_train)

acc = log_reg.score(X_test, y_test)
print(f"acc: {acc}")

acc: 0.596875


In [4]:
cm = confusion_matrix(y_test, log_reg.predict(X_test))
print(cm)

[[  0   0   1   0   0   0]
 [  0   0   3   3   0   0]
 [  0   0 108  38   0   0]
 [  0   0  46  71  11   0]
 [  0   0   2  22  12   0]
 [  0   0   0   2   1   0]]
